[package]
name = "rustclaw"
version = "0.1.0"
edition = "2021"

[dependencies]
rig-core = "0.30.0"
tokio = { version = "1", features = ["full"] } 
tokio-util = "0.7"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
fastembed = "4" 
dotenv = "0.15"  
serde_json = "1.0"
usearch = "2.13"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
